In [1]:
# install numpy 

%pip install numpy


[notice] A new release of pip is available: 25.3 -> 26.0
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
print(np.__version__)

2.3.5


In [13]:
# create a single dimensional array
data = [21,22,23,24,25]
print(data)
# check type 
print(type(data))

# access element
print(data[0])
print(data[1])
print(data[2])

[21, 22, 23, 24, 25]
<class 'list'>
21
22
23


In [14]:
data = np.array([21,22,23,24,25])
print(data)
# check type 
print(type(data))

# check dimension
print(data.ndim)
# shape of array
print(data.shape)
# size of array
print(data.size)

# access element
print(data[0])
print(data[1])
print(data[2])

[21 22 23 24 25]
<class 'numpy.ndarray'>
1
(5,)
5
21
22
23


In [16]:
# 2 dimensional array
data = np.array([[21,22,23],[24,25,26],[27,28,29]])
print(data)
# check dimension
print(data.ndim)
# shape of array
print(data.shape)
# size of array
print(data.size)

# access element
print(data[0][0])
print(data[2][1])
print(data[0][2])

[[21 22 23]
 [24 25 26]
 [27 28 29]]
2
(3, 3)
9
21
28
23


In [19]:
# 3 dimensional array
data = np.array([[
    [21,22,23],
    [24,25,26],
    [27,28,29]],
                 [[2,3,53],
                  [54,15,76],
                  [77,98,89]]])
print(data)
# check dimension
print(data.ndim)
# shape of array
print(data.shape)
# size of array
print(data.size)

# access element
print(data[0][0][0])

print(data[1][0][0])

[[[21 22 23]
  [24 25 26]
  [27 28 29]]

 [[ 2  3 53]
  [54 15 76]
  [77 98 89]]]
3
(2, 3, 3)
18
21
2


In [21]:
# 4 dimensional array
data = np.array([[[
    [21,22,23],
    [24,25,26],
    [27,28,29]],
                 [[21,22,23],
                  [24,25,26],
                  [27,28,29]]],
                [[
    [21,22,23],
    [24,25,26],
    [27,28,29]],
                 [[21,22,23],
                  [24,25,26],
                  [27,28,29]]]])
print(data)
# check dimension
print(data.ndim)
# shape of array
print(data.shape)
# size of array
print(data.size)

# access element
print(data[0][0][0][0])

print(data[1][0][0][0])

[[[[21 22 23]
   [24 25 26]
   [27 28 29]]

  [[21 22 23]
   [24 25 26]
   [27 28 29]]]


 [[[21 22 23]
   [24 25 26]
   [27 28 29]]

  [[21 22 23]
   [24 25 26]
   [27 28 29]]]]
4
(2, 2, 3, 3)
36
21
21
