In [1]:
# install numpy

%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

print(np.__version__)

2.2.4


In [3]:
# single array 
data = np.array([23,34,56,78,90])
print(data)

[23 34 56 78 90]


In [4]:
# check type 
print(type(data))

<class 'numpy.ndarray'>


In [9]:
# 2d array
data = np.array([[12,23,24,25],[12,13,14,15]])
print(data)

[[12 23 24 25]
 [12 13 14 15]]


In [12]:
print(data[1][2])
print(data[0][3])

14
25


In [27]:
data = np.array([[12,23,24,25],[11,13,14,15],[10,30,55,77],[99,89,80,68]])
print(data)

[[12 23 24 25]
 [11 13 14 15]
 [10 30 55 77]
 [99 89 80 68]]


In [28]:
print(data[2,2])

55


In [29]:
print("Dimension:", data.ndim)

Dimension: 2


In [24]:
# 3d array
data = np.array([[[12,23,24,25],[12,13,14,15]],[[12,23,24,25],[12,13,14,15]],[[12,23,24,25],[12,13,14,15]],[[12,23,24,25],[12,13,14,15]]])
print(data)

[[[12 23 24 25]
  [12 13 14 15]]

 [[12 23 24 25]
  [12 13 14 15]]

 [[12 23 24 25]
  [12 13 14 15]]

 [[12 23 24 25]
  [12 13 14 15]]]


In [25]:
print("Dimension:", data.ndim)

Dimension: 3


In [ ]:
# Array of zeros
zeros = np.zeros((3, 3))  # 3 rows, 3 columns
print("Zeros Array:\n", zeros)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [19]:
# Array of ones
ones = np.ones((3, 2))  # 3 rows, 2 columns
print("Ones Array:\n", ones)

Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [20]:
# Array with a range of numbers
range_array = np.arange(0, 10, 2)  # Start at 0, end before 10, step by 2
print("Range Array:", range_array)

Range Array: [0 2 4 6 8]


In [21]:
# Array with evenly spaced numbers
linspace_array = np.linspace(0, 1, 5)  # 5 numbers from 0 to 1
print("Linspace Array:", linspace_array)

Linspace Array: [0.   0.25 0.5  0.75 1.  ]


In [22]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", array)
print("Shape:", array.shape)  # Number of rows and columns
print("Size:", array.size)    # Total number of elements
print("Data type:", array.dtype)  # Type of elements
print("Dimension:", array.ndim)   # Number of dimensions

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data type: int64
Dimension: 2
