In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
# array 
import numpy as np

data1 = np.array([12,13,14,15,16])
print(data1)

# check type 
print(type(data1))



[12 13 14 15 16]
<class 'numpy.ndarray'>


In [7]:
# access data 
print(data1[2])

14


In [9]:
data = np.array([[12,13,14],[15,16,17],[18,19,20]]) # 3X3
print(data)

# access data 
print(data[1,2])

[[12 13 14]
 [15 16 17]
 [18 19 20]]
17


In [11]:
# check dimesions 
print(data1.ndim)
print(data.ndim)

1
2


In [23]:
data = np.array([[[12,13,14],[15,16,17],[18,19,20]],[[1,3,4],[5,6,7],[8,9,0]]]) # 3X3
print(data)
print(data.ndim)
# acess data 
print(data[0,1][2])

[[[12 13 14]
  [15 16 17]
  [18 19 20]]

 [[ 1  3  4]
  [ 5  6  7]
  [ 8  9  0]]]
3
17


In [25]:
print(data[0,1][1])

16


In [29]:
zeros = np.zeros((3,3),dtype=int)
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [30]:
one = np.ones((3,3),dtype=int)
one

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [32]:
# indentity matrix
i = np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
# range values - 
# arange(start,stop,step=2)
arange = np.arange(0,10,2) 
print(arange)

[0 2 4 6 8]


In [34]:
# random array
random = np.random.rand(2,2)
print(random)

[[0.8007625  0.62370612]
 [0.94813235 0.66218719]]


In [35]:
print(random.size)

4


In [39]:
# Element wise operations
data1 = np.array([10,20,30])
data2 = np.array([20,30,40])

# addition 
print(data1+data2)
# multiplication
print(data1*data2)
# Exponentiation 
print(data1 **2)

[30 50 70]
[ 200  600 1200]
[100 400 900]


In [42]:
print(np.sqrt(data1))
print(np.sin(data1))

[3.16227766 4.47213595 5.47722558]
[-0.54402111  0.91294525 -0.98803162]


In [46]:
data = np.array([[1,2,3],[4,5,6]])
scalar = 10
print(data+scalar)

row_vec = np.array([30,40,60])
print(data+row_vec)

[[11 12 13]
 [14 15 16]]
[[31 42 63]
 [34 45 66]]


In [51]:
flat = np.arange(12)
print(flat)
re = flat.reshape([3,4])
print(re)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [56]:
data = np.array([12,13,14,15,16])
print(np.sum(data))
print(np.mean(data))
print(np.std(data))
print(np.min(data))
print(np.max(data))



70
14.0
1.4142135623730951
12
16


In [105]:
data = np.random.default_rng(seed=42)
print(data.integers(0,100))

8


In [114]:
# random choice from array
d = np.array(["apple","banana","cherry","cherry"])
print(data.choice(d,size=1))

['cherry']


In [124]:
shuffle_arr = np.arange(10)
data.shuffle(shuffle_arr)
print(shuffle_arr)

[6 0 2 8 3 4 1 9 5 7]


In [ ]:
# https://cwpc.in/numpy-random-681071ee5abd
# https://cwpc.in/mastering-numpy-a-comprehensive-guide-codes-with-pankaj-178e191a9143