In [80]:
# import numpy as np
import numpy as np
from numpy import random

x = random.randint(100)
print(x)

x = random.rand()
print(x)

57
0.4514366956053003


In [ ]:
x = random.randint(100,size=(3,5))
print(x)

In [ ]:
# Float Array 
x = random.rand(5)
print(x)

# create 2d array 
x = random.rand(3,5)
print(x)

In [43]:
# single values 
x = random.choice([3,4,5,6,7,8,9,10])
print(x)

8


In [79]:
# array of values 2d array 
x = random.choice([1,2,3,4],size=(3,3))
print(x)

[[1 3 2]
 [3 4 2]
 [1 1 1]]


In [95]:
color = ['red','green','blue','lightgreen','pink']
selected = np.random.choice(color,size=3)
print(selected)

['green' 'green' 'red']


In [ ]:
# shuffle an array 
arr = np.array([21,22,23,24,25])
np.random.shuffle(arr)
print(arr)

# permuation
new_arr = np.random.permutation(arr)
print(new_arr)

[24 25 21 22 23]
[24 25 23 21 22]


In [205]:
# seed()
np.random.seed(42)
x = np.random.randint(1,100)
print(x)


52
