In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.2


In [3]:
# Creating NumPy Arrays :
arr = np.array(34)
print(arr)

34


In [4]:
# 1-D Arrays :
d1 = np.array([34,56,78,90,12])
print(d1)

[34 56 78 90 12]


In [6]:
# 2-D Arrays:
d2 = np.array([[34,56,78],[55,77,88],[56,89,90]])
print(d2)

[[34 56 78]
 [55 77 88]
 [56 89 90]]


In [13]:
print(d2[1][2])
print(d2.ndim)

88
2


In [12]:
# 3-D Arrays:

d3 = np.array([[[12,34,56],[45,56,89]],[[12,34,56],[45,56,89]],[[12,34,56],[45,56,89]],[[12,34,56],[45,56,89]]])
print(d3)

print(d3.ndim)

[[[12 34 56]
  [45 56 89]]

 [[12 34 56]
  [45 56 89]]

 [[12 34 56]
  [45 56 89]]

 [[12 34 56]
  [45 56 89]]]
3


In [3]:
import numpy as np

# Creating array object

arr = np.array( [[ 1, 2, 3],[ 4, 2, 5]] )
print(arr)

[[1 2 3]
 [4 2 5]]


In [4]:
# Printing type of arr object

print("Array is of type: ", type(arr))

Array is of type:  <class 'numpy.ndarray'>


In [5]:
# Printing array dimensions (axes)

print("No. of dimensions: ", arr.ndim)

No. of dimensions:  2


In [6]:
# Printing shape of array

print("Shape of array: ", arr.shape)

Shape of array:  (2, 3)


In [7]:
# Printing size (total number of elements) of array

print("Size of array: ", arr.size)

Size of array:  6


In [8]:
# Printing type of elements in array

print("Array stores elements of type: ", arr.dtype)

Array stores elements of type:  int32


In [10]:
# Creating array from list with type float

a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')

print ("Array created using passed list:\n", a)
print(a.dtype)

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]
float64


In [11]:
# Creating array from tuple

b = np.array((1 , 3, 2))

print ("\nArray created using passed tuple:\n", b)


Array created using passed tuple:
 [1 3 2]


In [12]:
# Creating a 3X4 array with all zeros

c = np.zeros((3, 4))

print ("\nAn array initialized with all zeros:\n", c)


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
# Create a constant value array of complex type

d = np.full((3, 3), 6, dtype = 'complex')

print ("\nAn array initialized with all 6s."

			"Array type is complex:\n", d)


An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [45]:
# Create an array with random values

e = np.random.random((2, 2))

print ("\nA random array:\n", e)


A random array:
 [[0.63822312 0.18217114]
 [0.90676294 0.17982488]]


In [51]:
# numpy.random.randint() function 
  

  
# output array 
out_arr = np.random.randint(11   , 99, (2                , 4    , 4)) 
#                           start end   number of array    row    col  
print ("Output 3D Array filled with random integers : ", out_arr)  

Output 3D Array filled with random integers :  [[[90 88 61 85]
  [93 98 23 96]
  [58 24 93 32]
  [73 94 18 27]]

 [[21 82 40 93]
  [15 47 74 89]
  [42 18 97 72]
  [78 79 55 77]]]


In [55]:
# Create a sequence of integers

# from 0 to 30 with steps of 5

f = np.arange(0, 50, 5)

print ("\nA sequential array with steps of 5:\n", f)


A sequential array with steps of 5:
 [ 0  5 10 15 20 25 30 35 40 45]


In [56]:
# Create a sequence of 10 values in range 0 to 5

g = np.linspace(0, 5, 10)

print ("\nA sequential array with 10 values between"

				"0 and 5:\n", g)


A sequential array with 10 values between0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [ ]:
# Reshaping 3X4 array to 2X2X3 array

arr = np.array([[1, 2, 3, 4],

		[5, 2, 4, 2],

		[1, 2, 0, 1]])