In [2]:
# install numpy
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
# check numpy version
import numpy as np
print(np.__version__)

2.2.4


In [ ]:
# create a numpy array
arr = np.array([1, 2, 3, 4, 5])
print(arr)
# check the type of the array
print(type(arr))
# check the shape of the array
print(arr.shape)
# check the data type of the array
print(arr.dtype)
# check the size of the array
print(arr.size)
# check the item size of the array
print(arr.itemsize)
# check the number of dimensions of the array
print(arr.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
int64
5
8
1


In [9]:
# multidimensional array
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2)
# check the shape of the array
print(arr2.shape)
# check the data type of the array
print(arr2.dtype)
# check the size of the array
print(arr2.size)
# check the item size of the array
print(arr2.itemsize)
# check the number of dimensions of the array
print(arr2.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
int64
9
8
2


In [8]:
# 2d array
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3)
# check the shape of the array
print(arr3.shape)
# check demensions
print(arr3.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [10]:
# 3d array
arr4 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr4)
# check the shape of the array
print(arr4.shape)
# check the number of dimensions of the array
print(arr4.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
3


In [11]:
# 4d array
arr5 = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]])
print(arr5)
# check the shape of the array
print(arr5.shape)
# check the number of dimensions of the array
print(arr5.ndim)

[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]
(1, 2, 2, 2)
4


In [20]:
# maths operations in numpy
arr6 = np.array([1, 2, 3, 4, 5])
print(arr6 + 5)  # add 5 to each element

# subtract 5 from each element
print(arr6 - 5)

# multiply each element by 5
print(arr6 * 5)

# divide each element by 5
print(arr6 / 5)

# raise each element to the power of 2
print(arr6 ** 2)

# find the square root of each element
print(np.sqrt(arr6))

# find the sum of all elements
print(np.sum(arr6))

# find the mean of all elements
print(np.mean(arr6))

# find the median of all elements
print(np.median(arr6))

[ 6  7  8  9 10]
[-4 -3 -2 -1  0]
[ 5 10 15 20 25]
[0.2 0.4 0.6 0.8 1. ]
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
15
3.0
3.0


In [26]:
# random numbers
arr7 = np.random.rand(5)  # generate 5 random numbers between 0 and 1
print(arr7)

# generate 5 random integers between 0 and 10
arr8 = np.random.randint(0, 10, 5)
print(arr8)

# generate a 2d array of random numbers
arr9 = np.random.rand(3, 3)  # 3x3 array of random numbers between 0 and 1
print(arr9)

# generate a 2d array of random integers between 0 and 10
arr10 = np.random.randint(0, 10, (3, 3))
print(arr10)

[0.90118629 0.71915897 0.24373453 0.45543835 0.50643571]
[3 4 2 5 5]
[[0.307587   0.43455816 0.01596235]
 [0.93636585 0.52070785 0.68739131]
 [0.21751107 0.65055805 0.51734293]]
[[9 2 9]
 [9 5 1]
 [0 2 8]]


In [28]:
# zeros array
arr11 = np.zeros((3, 3))  # 3x3 array of zeros
print(arr11)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [30]:
# generate an array of ones
arr12 = np.ones((3, 3))  # 3x3 array of ones
print(arr12)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [31]:
# Array with evenly spaced numbers
arr13 = np.arange(0, 10, 2)  # start, stop, step
print(arr13)

[0 2 4 6 8]


In [32]:
# minimum and maximum of an array
arr14 = np.array([1, 2, 3, 4, 5])
print(np.min(arr14))  # minimum value
print(np.max(arr14))  # maximum value

1
5
