In [2]:
# numpy in python
# numpy is a library for the Python programming language, adding support for large, multi-dimensional arrays and
# matrices, along with a large collection of high-level mathematical functions to operate on these arrays.
# https://numpy.org/
# install numpy
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

# check numpy version
print("Numpy version:", np.__version__)

Numpy version: 2.2.4


In [4]:
# create a numpy array
arr = np.array([1, 2, 3, 4, 5])

# print the array
print("Numpy array:", arr)

Numpy array: [1 2 3 4 5]


In [6]:
# 2d array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# print the 2d array
print("2D Numpy array:\n", arr_2d)

2D Numpy array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
# accessing elements
print("Element at (0, 1):", arr_2d[0, 1])  # Accessing element at row 0, column 1

# access 5 numbers
print(arr_2d[1,1])  


Element at (0, 1): 2
5


In [9]:
# check Dimensions 
print("Dimensions of arr_2d:", arr_2d.ndim)  # Number of dimensions

Dimensions of arr_2d: 2


In [10]:
# check the shape of the array
print("Shape of 2D array:", arr_2d.shape)

Shape of 2D array: (3, 3)


In [11]:
# perform basic operations
# add 2 to each element
arr_plus_2 = arr + 2
print("Array after adding 2:", arr_plus_2)

Array after adding 2: [3 4 5 6 7]


In [12]:
# 2d array addition
arr_2d_plus_2 = arr_2d + 2 
print("2D Array after adding 2:\n", arr_2d_plus_2)

2D Array after adding 2:
 [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [13]:
# manipulate the array
arr = arr * 2
print("Array after multiplying by 2:", arr)
# 2d array multiplication  
arr = arr * 2
print("2D Array after multiplying by 2:\n", arr_2d * 2)

Array after multiplying by 2: [ 2  4  6  8 10]
2D Array after multiplying by 2:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [14]:
# zeros array
zeros_array = np.zeros((3, 3))  # Create a 3x3 array of zeros
print("3x3 Array of zeros:\n", zeros_array)

3x3 Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
# ones array
ones_array = np.ones((2, 4))  # Create a 2x4 array of ones
print("2x4 Array of ones:\n", ones_array)

2x4 Array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
# random array
random_array = np.random.rand(3, 3)  # Create a 3x3 array of random floats
print("3x3 Array of random floats:\n", random_array)

3x3 Array of random floats:
 [[0.62478815 0.81300297 0.59104626]
 [0.61493888 0.06570633 0.97290026]
 [0.22768621 0.36627237 0.30568376]]


In [29]:
# random array integer
arr = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
random_int_array = np.random.choice(arr, size=(3, 3), replace=False)  # Create a 3x3 array of random integers
print("3x3 Array of random integers:\n", random_int_array)

3x3 Array of random integers:
 [[ 5  6  1]
 [ 3  9  8]
 [10  2  4]]


In [30]:
# Ellipsis (…) Indexing 
# Create a 3D array
three_d_array = np.random.rand(2, 3, 4)  # 2x3x4 array of random floats
print("3D Array:\n", three_d_array)
# Accessing all elements in the second dimension using Ellipsis
print("Accessing all elements in the second dimension:\n", three_d_array[..., 1])  # Accessing all elements in the second dimension

3D Array:
 [[[0.08632614 0.54507178 0.62324463 0.39372562]
  [0.6623341  0.01761548 0.46987873 0.67724972]
  [0.2262496  0.78953657 0.04335852 0.6374155 ]]

 [[0.32706643 0.59794318 0.03707852 0.5970671 ]
  [0.80704221 0.13555004 0.59558967 0.70801319]
  [0.52596247 0.17511052 0.16857647 0.10324734]]]
Accessing all elements in the second dimension:
 [[0.54507178 0.01761548 0.78953657]
 [0.59794318 0.13555004 0.17511052]]
