In [1]:
# numpy in python 

# imstall numpy 

%pip install numpy



[notice] A new release of pip is available: 24.2 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
# verify the installation
import numpy as np

In [3]:
# check version

print(np.__version__)

2.2.1


In [8]:
# create a numpy array

# single array 

a = np.array([1,2,3,4,5])
print(a)

# Check Number of Dimensions :
print(a.ndim)

[1 2 3 4 5]
1


In [9]:
# 2d array

b = np.array([[1,2,3,4,5],[6,7,8,9,10]],)
print(b)

# Check Number of Dimensions :
print(b.ndim)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


In [10]:
# 3d array

c = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(c)

# Check Number of Dimensions :
print(c.ndim)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
3


In [11]:
# 4d array

d = np.array([[[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]],[[[21,22,23,24,25],[26,27,28,29,30]],[[31,32,33,34,35],[36,37,38,39,40]]]])
print(d)

# Check Number of Dimensions :
print(d.ndim)

[[[[ 1  2  3  4  5]
   [ 6  7  8  9 10]]

  [[11 12 13 14 15]
   [16 17 18 19 20]]]


 [[[21 22 23 24 25]
   [26 27 28 29 30]]

  [[31 32 33 34 35]
   [36 37 38 39 40]]]]
4


In [14]:
# Higher-Dimensional Arrays :

# 5d array
arr_nd = np.array([[[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]],[[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]]])
print(arr_nd)

# check number of dimensions
print(arr_nd.ndim)

[[[[[ 1  2]
    [ 3  4]]

   [[ 5  6]
    [ 7  8]]]


  [[[ 9 10]
    [11 12]]

   [[13 14]
    [15 16]]]]



 [[[[ 1  2]
    [ 3  4]]

   [[ 5  6]
    [ 7  8]]]


  [[[ 9 10]
    [11 12]]

   [[13 14]
    [15 16]]]]]
5


In [16]:
# index          0 1 2 3 4
data = np.array([1,2,3,4,5])

# NumPy Array Indexing :

# Accessing 1D Array Elements :
print(data[0])  # Output: 1

print(data[1])  # Output: 2


1
2


In [17]:
# Slicing :
print(data[1:4])  # Output: [2 3 4]

[2 3 4]


In [ ]:
# Boolean Indexing :

print(data[data > 2])  # Output: [3 4 5]

In [19]:
# Integer Array Indexing :
#   - Indexing is 0-based, meaning the first element is at index 0.
#   - Negative indexing means starting from the end of the array.
#   - Slicing is used to extract a subset of elements from the array.

# Accessing 2D Array Elements :

data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(data[0, 0])  # Output: 1

print(data[1, 1])  # Output: 5

1
5


In [20]:
# Slicing in Multidimensional Arrays :

print(data[0:2, 0:2])  # Output: [[1 2] [4 5]]

[[1 2]
 [4 5]]


In [23]:
# Ellipsis (…) Indexing 
data = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(data[0, 1, 1])  # Output: 5

print(data[1, ...])  # Output: [[ 7  8  9] [10 11 12]]

5
[[ 7  8  9]
 [10 11 12]]


In [24]:
# Checking the Data Type of an Array :

data = np.array([1, 2, 3, 4, 5])
print(data.dtype)  # Output: int32

int64


In [25]:
# Changing the Data Type of an Array :
# In this example, we will change the data type of an array from integer to float.

data = np.array([1, 2, 3, 4, 5])
data = data.astype('float')
print(data)

[1. 2. 3. 4. 5.]


In [27]:
# check array shape
print(data.shape)


(5,)


In [30]:
# NumPy Array Reshaping 

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)
print(arr)  
print(reshaped)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [31]:
# NumPy Array Iterating :

for i in arr:
    print(i)
    

1
2
3
4
5
6


In [34]:
# NumPy Searching Array

arr = np.array([1, 2, 3, 4, 5])
indexes = np.where(arr == 3)
print(indexes)




(array([2]),)
None


In [36]:
arr = np.array([3, 1, 2, 4, 5])
arr.sort() 
print(arr)

[1 2 3 4 5]
