In [ ]:
# Installation:

#     Mac and Linux users can install NumPy via pip command:
#     pip install numpy

In [7]:
# basic array characteristics
import numpy as np

In [15]:
# Creating array object
data = np.array([[ 1, 2, 3],[ 4, 2, 5],[ 6, 7, 8]]) 

# Printing type of arr object
print("Array is of type: ", type(data))

Array is of type:  <class 'numpy.ndarray'>


In [16]:
# Printing array dimensions (axes)
print("No. of dimensions: ", data.ndim)

No. of dimensions:  2


In [17]:
# Printing shape of array
print("Shape of array: ", data.shape)

Shape of array:  (3, 3)


In [18]:
# Printing size (total number of elements) of array

print("Size of array: ", data.size)

Size of array:  9


In [19]:
# Printing type of elements in array
print("Array stores elements of type: ", data.dtype)

Array stores elements of type:  int64


In [22]:
# Creating array from list with type float

a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float') # str

print ("Array created using passed list:\n", a)

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]


In [23]:
# Creating array from tuple

b = np.array((1 , 3, 2))

print ("\nArray created using passed tuple:\n", b)


Array created using passed tuple:
 [1 3 2]


In [25]:
# Creating a 3X4 array with all zeros

c = np.zeros((4, 5))

print ("\nAn array initialized with all zeros:\n", c)


An array initialized with all zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
# Create a constant value array of complex type

d = np.full((3, 3), 6, dtype = 'complex')

print ("\nAn array initialized with all 6s."

			"Array type is complex:\n", d)


An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [ ]:
# Create an array with random values

e = np.random.random((2, 2))

print ("\nA random array:\n", e)