In [2]:
# %pip install numpy
import numpy as np

In [9]:
# create a array 
a = np.array([1,2,3,4])
print(a)
# check type 
print(type(a))
# access data
print(a[3])
# check shap
print(a.shape)
# check data type
print(a.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
4
(4,)
int64


In [13]:
# create a array 2d
a = np.array([[21,22,23],[24,25,26],[27,28,29]])
print(a)
# check type 
print(type(a))
# access data
print(a[1][1])
# check shap
print(a.shape)
# check data type
print(a.dtype)
# check dim
print(a.ndim)

[[21 22 23]
 [24 25 26]
 [27 28 29]]
<class 'numpy.ndarray'>
25
(3, 3)
int64
2


In [16]:
# create a array 3d
a = np.array([[[21,22,23],[24,25,26],[27,28,29]],[[21,22,23],[24,25,26],[27,28,29]]])
print(a)
# check type 
print(type(a))
# access data
print(a[1][1])
# check shap
print(a.shape)
# check data type
print(a.dtype)
# check dim
print(a.ndim)

[[[21 22 23]
  [24 25 26]
  [27 28 29]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
<class 'numpy.ndarray'>
[24 25 26]
(2, 3, 3)
int64
3
