In [1]:
import numpy as np

print(np.__version__)

2.3.2


In [3]:
# create a array
arr1 = np.array([11,22,33,44,55])
print(arr1)
# check type 
print(type(arr1))

[11 22 33 44 55]
<class 'numpy.ndarray'>


In [5]:
# create a 2d array 
arr2 = np.array([[11,22,33],[44,55,66],[77,88,99]])
print(arr2)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [6]:
# create a zero array 
arr3 = np.zeros([3,3])
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# ones array 
data = np.ones((5,3))
print(data)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
# range 
arr_range = np.arange(0,10,2)
print(arr_range)

[0 2 4 6 8]


In [14]:
arr2 = np.array([[11,22,33],[44,55,66],[77,88,99]])
print(arr2)
# shape
print(arr2.shape)
# size 
print(arr2.size)
# check datatype
print(arr2.dtype)
# dimensions
print(arr2.ndim)

[[11 22 33]
 [44 55 66]
 [77 88 99]]
(3, 3)
9
int64
2


In [24]:
# operations 
data = np.array([12,13,14,15,16,17])
print(data)
print(data+10)
print(data*4)
print(data**3)

# mathematical operations 
# sum()
print(np.sum(data))
# mean()
print(np.mean(data))
# max
print(np.max(data))
# min
print(np.min(data))
# square
print(np.sqrt(data))

[12 13 14 15 16 17]
[22 23 24 25 26 27]
[48 52 56 60 64 68]
[1728 2197 2744 3375 4096 4913]
87
14.5
17
12
[3.46410162 3.60555128 3.74165739 3.87298335 4.         4.12310563]


In [49]:
# random numbers 
data = np.random.rand(2,3)
print(data)

# int random number 
data = np.random.randint(1,10,size=(3,3))
print(data)

[[0.71217922 0.23724909 0.3253997 ]
 [0.74649141 0.6496329  0.84922341]]
[[1 1 3]
 [6 7 6]
 [6 6 3]]


In [33]:
np.random.seed(42)
random_data = np.random.rand(3)
print(random_data)

[0.37454012 0.95071431 0.73199394]


In [58]:
rand_ints = np.random.randint(low=10,high=50,size=5)
print(rand_ints)

[36 11 35 26 49]


In [123]:
# random choice

data = np.array([10,20,30,40,50,60,70,80])
print(data)
choices = np.random.choice(data,size=4,replace=True)
print(choices)

choices2 = np.random.choice(data,size=4,replace=False)
print(choices2)

[10 20 30 40 50 60 70 80]
[60 70 20 30]
[30 60 80 20]
