In [1]:
# install numpy
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [9]:
# import numpy as np
from numpy import random
x = random.randint(100)
print(x)

40


In [24]:
# generate Random Float
x = random.rand()
print(x*89)

17.41009589877908


In [44]:
# random integer array
x = random.randint(1000,size=(10))
print(x)

[653 218 696 933 744 152 486 719 218 893]


In [50]:
# 2d array (row,col)
x = random.randint(100,size=(5,4))
print(x)

[[15  8 60 75]
 [24 48 94 78]
 [ 7 25 35 10]
 [86 74 68 32]
 [35 59 65 58]]


In [56]:
# float array 
x = random.rand(5)
print(x)
# 2d array 
x = random.rand(3,5)
print(x)

[0.54829852 0.0884116  0.67328725 0.22102198 0.33576492]
[[0.11561947 0.06049012 0.72918823 0.39106998 0.37101983]
 [0.19867798 0.37191539 0.4487756  0.88403116 0.44198129]
 [0.75710028 0.45138779 0.90017717 0.14935769 0.14591559]]


In [65]:
# choice item 
x = random.choice([21,22,23,24,25,26,27])
print(x)

# 2d array choice item
x = random.choice([21,22,23,34,35,36,16,17],size=(3,5))
print(x)

26
[[36 21 22 23 22]
 [17 17 16 36 22]
 [23 23 21 17 17]]
