In [1]:
# install numpy

%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

print(np.__version__)

2.2.4


In [3]:
# single array 
data = np.array([23,34,56,78,90])
print(data)

[23 34 56 78 90]


In [4]:
# check type 
print(type(data))

<class 'numpy.ndarray'>


In [5]:
# 2d array
data = np.array([[12,23,24,25],[12,13,14,15]])
print(data)

[[12 23 24 25]
 [12 13 14 15]]


In [6]:
print(data[1][2])
print(data[0][3])

14
25


In [7]:
data = np.array([[12,23,24,25],[11,13,14,15],[10,30,55,77],[99,89,80,68]])
print(data)

[[12 23 24 25]
 [11 13 14 15]
 [10 30 55 77]
 [99 89 80 68]]


In [8]:
print(data[2,2])

55


In [9]:
print("Dimension:", data.ndim)

Dimension: 2


In [10]:
# 3d array
data = np.array([[[12,23,24,25],[12,13,14,15]],[[12,23,24,25],[12,13,14,15]],[[12,23,24,25],[12,13,14,15]],[[12,23,24,25],[12,13,14,15]]])
print(data)

[[[12 23 24 25]
  [12 13 14 15]]

 [[12 23 24 25]
  [12 13 14 15]]

 [[12 23 24 25]
  [12 13 14 15]]

 [[12 23 24 25]
  [12 13 14 15]]]


In [11]:
print("Dimension:", data.ndim)

Dimension: 3


In [12]:
# Array of zeros
zeros = np.zeros((3, 3))  # 3 rows, 3 columns
print("Zeros Array:\n", zeros)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
# Array of ones
ones = np.ones((3, 2))  # 3 rows, 2 columns
print("Ones Array:\n", ones)

Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [14]:
# Array with a range of numbers
range_array = np.arange(0, 10, 2)  # Start at 0, end before 10, step by 2
print("Range Array:", range_array)

Range Array: [0 2 4 6 8]


In [15]:
# Array with evenly spaced numbers
linspace_array = np.linspace(0, 1, 5)  # 5 numbers from 0 to 1
print("Linspace Array:", linspace_array)

Linspace Array: [0.   0.25 0.5  0.75 1.  ]


In [16]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", array)
print("Shape:", array.shape)  # Number of rows and columns
print("Size:", array.size)    # Total number of elements
print("Data type:", array.dtype)  # Type of elements
print("Dimension:", array.ndim)   # Number of dimensions

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Data type: int64
Dimension: 2


In [18]:
# array operations 
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)
print(a-b)

[5 7 9]
[-3 -3 -3]


In [19]:
# scalar operations 
print(a*2)

[2 4 6]


In [21]:
# Reshape and flatten array 
a = np.array([[1,2],[3,4],[5,6]])
print(a.reshape(2,3))
print(a.flatten())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
# matrix operations 
data1 = np.array([[1,2],[3,4]])
data2 = np.array([[2,0],[1,3]])

print(np.dot(data1,data2)) # matrix multiplications
print(np.transpose(data1)) # transpose of data 1

[[ 4  6]
 [10 12]]
[[1 3]
 [2 4]]


In [24]:
# random modules 
# random flot number between 0 and 1
print(np.random.rand(3))

[0.90430091 0.26318197 0.6246829 ]


In [26]:
# random integers between 1 and 10 
print(np.random.randint(1,10,size=(2,3)))

[[6 1 7]
 [5 1 9]]


In [27]:
# random numbers form normal distribution
print(np.random.randn(2,2)) 

[[-0.69728293 -0.7339458 ]
 [-1.75735003 -1.23322614]]


In [28]:
# set seed for reproducidility
np.random.seed(42)
print(np.random.randint(0.100,5))

3


In [31]:
# using math function 
arr = np.array([1,4,9,16])
# square root 
print(np.sqrt(arr))
# natural log 
print(np.log(arr))
# exponential 
print(np.exp(arr))

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
