In [1]:
# %pip install numpy

In [2]:
import numpy as np

In [3]:
# array 
data = np.array([21,22,23,24,25])
print(data)
print(data[3])
print(type(data))
print(data.shape)
print(data.size)
print(data.ndim)

[21 22 23 24 25]
24
<class 'numpy.ndarray'>
(5,)
5
1


In [4]:
data = np.array([[21,22,23],[24,25,26],[27,28,29]])
print(data.shape)
print(data)
print(data[1,1])
print(data.size)
print(data.ndim)

(3, 3)
[[21 22 23]
 [24 25 26]
 [27 28 29]]
25
9
2


In [5]:
data = np.array([[[21,22,23],[24,25,26],[27,28,29]],
                 [[21,22,23],[24,25,26],[27,28,29]]])
print(data.shape)
print(data.size)
print(data.ndim)

(2, 3, 3)
18
3


In [6]:
data = np.array([[[[21,22,23],[24,25,26],[27,28,29]],
                 [[21,22,23],[24,25,26],[27,28,29]]],
               [[[21,22,23],[24,25,26],[27,28,29]],
                 [[21,22,23],[24,25,26],[27,28,29]]]])
print(data.shape)
print(data.size)
print(data.ndim)

(2, 2, 3, 3)
36
4


In [9]:
# arange(start,stop,step,dtype=None)
data = np.arange(0,10,2,dtype=int)
print(data)

[0 2 4 6 8]


In [16]:
data = np.arange(0.5,5.5,1.0)
print(data)

[0.5 1.5 2.5 3.5 4.5]


In [17]:
data = np.arange(10,0,-2)
print(data)

[10  8  6  4  2]


In [22]:
# np.linespace(start,stop,num=50,endpoint=True,restep=False,dtype=None)

data , step = np.linspace(0,10,5,endpoint=False,retstep=True)
print(data)
print("Step Size : ",step)

[0. 2. 4. 6. 8.]
Step Size :  2.0


In [ ]:
data = np.logspace(1,10,4,base=10)
print(data)

[1.e+01 1.e+04 1.e+07 1.e+10]
