In [1]:
%pip install numpy


[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

print(np.__version__)

2.3.5


In [13]:
# create a single array 1D 

arr_1 = np.array([23,24,25,26,27,28,29])
print(arr_1)

# check type 
print(type(arr_1))
# dimensions
print(np.ndim(arr_1))
# check size 
print(arr_1.size)
# check column and row
print(arr_1.shape)

# access data from array 

print(arr_1[3])


[23 24 25 26 27 28 29]
<class 'numpy.ndarray'>
1
7
(7,)
26


In [14]:
arr_1 = np.array([[12,13,14],[34,35,36],[45,46,47]])
print(arr_1)

# check type 
print(type(arr_1))
# dimensions
print(np.ndim(arr_1))
# check size 
print(arr_1.size)
# check column and row
print(arr_1.shape) # (row,col)

print(arr_1[1,1])

[[12 13 14]
 [34 35 36]
 [45 46 47]]
<class 'numpy.ndarray'>
2
9
(3, 3)
35


In [ ]:
arr_1 = np.array([[
                   [12,13,14],
                   [34,35,36],
                   [45,46,47]],
                  
                  [[52,53,54],
                   [24,55,56],
                   [55,56,57]]])

print(arr_1)

# check type 
print(type(arr_1))
# dimensions
print(np.ndim(arr_1))
# check size 
print(arr_1.size)
# check column and row
print(arr_1.shape) # (no_of_array,row,col)

print(arr_1[1][1,1])

[[[12 13 14]
  [34 35 36]
  [45 46 47]]

 [[52 53 54]
  [24 55 56]
  [55 56 57]]]
<class 'numpy.ndarray'>
3
18
(2, 3, 3)
55


In [16]:
arr_1 = np.array([[[
                   [12,13,14],
                   [34,35,36],
                   [75,76,77]],
                  
                  [[89,88,48],
                   [6,67,89],
                   [87,85,86]]],
                 [[
                   [22,23,24],
                   [24,25,26],
                   [25,26,27]],
                  
                  [[42,43,44],
                   [44,45,46],
                   [55,46,47]]]])

print(arr_1)

# dimensions
print(np.ndim(arr_1))
# check size 
print(arr_1.size)
# check column and row
print(arr_1.shape) # (section_of array,no_of_array,row,col)

print(arr_1[0][1][2,2])

[[[[12 13 14]
   [34 35 36]
   [75 76 77]]

  [[89 88 48]
   [ 6 67 89]
   [87 85 86]]]


 [[[22 23 24]
   [24 25 26]
   [25 26 27]]

  [[42 43 44]
   [44 45 46]
   [55 46 47]]]]
4
36
(2, 2, 3, 3)
86


In [ ]:
# https://cwpc.in/mastering-numpy-a-comprehensive-guide-codes-with-pankaj-178e191a9143