In [3]:
# install numpy 
%pip install numpy


[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [1]:
# check numpy version

import numpy as np
print(np.__version__)

2.3.5


In [2]:
data = np.array([1, 2, 3, 4, 5])
print(data)
print(data.ndim)  # number of dimensions
print(data.shape)  # shape of the array

[1 2 3 4 5]
1
(5,)


In [3]:
# data 2 d array
data_2d = np.array([
    [21,22,23],
    [24,25,26],
    [27,28,29] 
])
print(data_2d)
print(data_2d.ndim)  # number of dimensions
print(data_2d.shape)  # shape of the array

[[21 22 23]
 [24 25 26]
 [27 28 29]]
2
(3, 3)


In [7]:
# data 3 d array
data_3d = np.array([
    [[21,22,23],
    [24,25,26],
    [27,28,29]],
    [[121,122,123],
    [124,125,126],
    [127,128,129]] 
    
])
print(data_3d)
print(data_3d.ndim)  # number of dimensions
print(data_3d.shape)  # shape of the array


# accessing elements in 3d array

print(data_3d[0][1,1])  # first 2d array
print(data_3d[1][1,0])  # second 2d array


[[[ 21  22  23]
  [ 24  25  26]
  [ 27  28  29]]

 [[121 122 123]
  [124 125 126]
  [127 128 129]]]
3
(2, 3, 3)
25
124


In [10]:
# Slicing

data = np.array([1, 2, 3, 4, 5])
print(data[1:4])  # slicing from index 1 to 3
print(data[:3])
print(data[2:])

[2 3 4]
[1 2 3]
[3 4 5]


In [12]:

data_2d = np.array([
    [21,22,23],
    [24,25,26],
    [27,28,29]
])

# get 2nd row
print(data_2d[1])

# get 3rd column
print(data_2d[:, 2])

[24 25 26]
[23 26 29]


In [17]:
# Ellipsis (…) Indexing

data = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

print(data)

print(data[0, ..., 1])  # get the second element from each sub-array in the first dimension
print(data[1, ..., 0])  # get the first element from each sub-array

print(data[..., 2])  # get the third element from each sub-array in all dimensions


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[2 5]
[ 7 10]
[[ 3  6]
 [ 9 12]]
