In [1]:
# install numpy 
%pip install numpy


[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python3 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
# check numpy version

import numpy as np
print(np.__version__)

2.3.5


In [4]:
data = np.array([1, 2, 3, 4, 5])
print(data)
print(data.ndim)  # number of dimensions
print(data.shape)  # shape of the array

[1 2 3 4 5]
1
(5,)


In [6]:
# data 2 d array
data_2d = np.array([
    [21,22,23],
    [24,25,26],
    [27,28,29]
])
print(data_2d)
print(data_2d.ndim)  # number of dimensions
print(data_2d.shape)  # shape of the array

[[21 22 23]
 [24 25 26]
 [27 28 29]]
2
(3, 3)
