In [1]:
# %pip install numpy

In [2]:
import numpy as np

In [3]:
# array 
data = np.array([21,22,23,24,25])
print(data)
print(data[3])
print(type(data))
print(data.shape)
print(data.size)
print(data.ndim)

[21 22 23 24 25]
24
<class 'numpy.ndarray'>
(5,)
5
1


In [4]:
data = np.array([[21,22,23],[24,25,26],[27,28,29]])
print(data.shape)
print(data)
print(data[1,1])
print(data.size)
print(data.ndim)

(3, 3)
[[21 22 23]
 [24 25 26]
 [27 28 29]]
25
9
2


In [5]:
data = np.array([[[21,22,23],[24,25,26],[27,28,29]],
                 [[21,22,23],[24,25,26],[27,28,29]]])
print(data.shape)
print(data.size)
print(data.ndim)

(2, 3, 3)
18
3


In [6]:
data = np.array([[[[21,22,23],[24,25,26],[27,28,29]],
                 [[21,22,23],[24,25,26],[27,28,29]]],
               [[[21,22,23],[24,25,26],[27,28,29]],
                 [[21,22,23],[24,25,26],[27,28,29]]]])
print(data.shape)
print(data.size)
print(data.ndim)

(2, 2, 3, 3)
36
4


In [7]:
# arange(start,stop,step,dtype=None)
data = np.arange(0,10,2,dtype=int)
print(data)

[0 2 4 6 8]


In [8]:
data = np.arange(0.5,5.5,1.0)
print(data)

[0.5 1.5 2.5 3.5 4.5]


In [9]:
data = np.arange(10,0,-2)
print(data)

[10  8  6  4  2]


In [10]:
# np.linespace(start,stop,num=50,endpoint=True,restep=False,dtype=None)

data , step = np.linspace(0,10,5,endpoint=False,retstep=True)
print(data)
print("Step Size : ",step)

[0. 2. 4. 6. 8.]
Step Size :  2.0


In [11]:
data = np.logspace(1,10,4,base=10)
print(data)

[1.e+01 1.e+04 1.e+07 1.e+10]


In [24]:
# zeros(shape,dtype=float,order='C')

data = np.zeros((3,3),dtype=int)
print(data)
print(data.ndim)
print("------------------------")
data = np.zeros((3,3,2),dtype=int)
print(data)
print(data.ndim)

data = np.zeros((3,3,2,2),dtype=int)
print(data)
print(data.ndim)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
2
------------------------
[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]
3
[[[[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]]


 [[[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]]


 [[[0 0]
   [0 0]]

  [[0 0]
   [0 0]]

  [[0 0]
   [0 0]]]]
4


In [28]:
data = np.zeros(())
print(data)
print(data.ndim)

0.0
0


In [29]:
# ones(shape,dtype=float)

data = np.ones((3,2),dtype=int)
print(data)

[[1 1]
 [1 1]
 [1 1]]


In [ ]:
data = np.ones((2,),dtype=int)
print(data)

[1 1]


In [40]:
data = np.ones((0),dtype=int)
print(data)
print(data.ndim)

data = np.ones((0,0),dtype=int)
print(data)
print(data.ndim)

[]
1
[]
2


In [41]:
data = np.empty((2,2))
print(data)

[[1.e+01 1.e+04]
 [1.e+07 1.e+10]]


In [42]:
arr = np.full((3,3),np.pi)
print(arr)

[[3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]]


In [47]:
arr = np.full((3,3),'hello',dtype='U2')
print(arr)

[['he' 'he' 'he']
 ['he' 'he' 'he']
 ['he' 'he' 'he']]


In [51]:
data = np.identity(3 , dtype=int)
print(data)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [67]:
arr = np.arange(24)
re_arr = np.reshape(arr,(4,6),order='F')
print(arr)
print(re_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  4  8 12 16 20]
 [ 1  5  9 13 17 21]
 [ 2  6 10 14 18 22]
 [ 3  7 11 15 19 23]]


In [77]:
data = np.arange(24).reshape(2,3,4)
print(data)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [78]:
new_data = np.swapaxes(data,0,2)
print(new_data)

[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


In [85]:
a1 = np.array([[12,13,14],[15,16,17]])
a2 = np.array([[2,3,4],[5,6,7]])

concat = np.concatenate((a1,a2),axis=0)
print(concat)

[[12 13 14]
 [15 16 17]
 [ 2  3  4]
 [ 5  6  7]]
