In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [15]:
# array 
data = np.array([21,22,23,24,25])
print(data)
print(data[3])
print(type(data))
print(data.shape)
print(data.size)
print(data.ndim)

[21 22 23 24 25]
24
<class 'numpy.ndarray'>
(5,)
5
1


In [14]:
data = np.array([[21,22,23],[24,25,26],[27,28,29]])
print(data.shape)
print(data)
print(data[1,1])
print(data.size)
print(data.ndim)

(3, 3)
[[21 22 23]
 [24 25 26]
 [27 28 29]]
25
9
2


In [19]:
data = np.array([[[21,22,23],[24,25,26],[27,28,29]],
                 [[21,22,23],[24,25,26],[27,28,29]]])
print(data.shape)
print(data.size)
print(data.ndim)

(2, 3, 3)
18
3


In [20]:
data = np.array([[[[21,22,23],[24,25,26],[27,28,29]],
                 [[21,22,23],[24,25,26],[27,28,29]]],
               [[[21,22,23],[24,25,26],[27,28,29]],
                 [[21,22,23],[24,25,26],[27,28,29]]]])
print(data.shape)
print(data.size)
print(data.ndim)

(2, 2, 3, 3)
36
4
