In [14]:
from numpy import random

x = random.randint(500)
print(x)

2


In [23]:
# Float

x = random.rand()
print(x)

0.6281502554371585


In [31]:
x = random.randint(100, size=(5))
print(x)

[61 41 37 27 17]


In [36]:
d3 = random.randint(100,size=(3,3))
print(d3)


[[14 46 63]
 [32 35 95]
 [81  1 99]]


In [46]:
x = random.rand(5)
print(x)

[0.99123879 0.48396308 0.10200927 0.63567605 0.61232824]


In [52]:
x = random.rand(5,3)
print(x)

[[0.42299992 0.96849142 0.53631701]
 [0.93694108 0.96371718 0.93269157]
 [0.65320368 0.44073213 0.5902938 ]
 [0.08920813 0.38225484 0.51216417]
 [0.5867783  0.80157332 0.17501108]]


In [60]:
x = random.choice([3, 5, 7, 9])
print(x)

5


In [71]:
x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[3 9 7 7 9]
 [7 7 7 9 3]
 [3 7 9 7 9]]
