In [1]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
np.__version__

'2.3.2'

In [3]:
data = np.array([21,22,23,24,25])
print(data)
print(data.shape)
print(data.size)
print(data.ndim)

# access data from array 
print(data[3])

[21 22 23 24 25]
(5,)
5
1
24


In [4]:
data = np.array([[21,22,23],[24,25,26],[27,28,29]])
print(data)
print(data.shape)
print(data.size)
print(data.ndim)

print(data[2,2])

[[21 22 23]
 [24 25 26]
 [27 28 29]]
(3, 3)
9
2
29


In [5]:
# Generating an array of even numbers from 0 to 10 (exclusive), useful for indexing or loops.
arr = np.arange(0, 10, 2, dtype=int)
print(arr)

# Variation: Floating-point steps for non-integer sequences
arr_float = np.arange(0.5, 5.5, 1.0)
print(arr_float)

# Edge case: Negative step for descending order
arr_desc = np.arange(10, 0, -2)
print(arr_desc)

[0 2 4 6 8]
[0.5 1.5 2.5 3.5 4.5]
[10  8  6  4  2]


In [14]:
# Creating 5 evenly spaced points from 0 to 10, including endpoint. Useful for plotting functions.
arr, step = np.linspace(0, 10, 5, endpoint=True, retstep=True)
print(arr)
print("Step size:", step)

[ 0.   2.5  5.   7.5 10. ]
Step size: 2.5


In [17]:
# Edge case: Single point (num=1)
single = np.linspace(1, 5, 1)
print(single)

[1.]


In [18]:


# Generating 4 log-spaced points from 10^1 to 10^3 (base 10). Useful for logarithmic scales in data analysis.
arr = np.logspace(1, 3, 4, base=10)
print(arr)

# Variation: Base 2 for binary exponents
arr_base2 = np.logspace(0, 3, 4, base=2)
print(arr_base2)

# Edge case: Excluding endpoint
arr_no_end = np.logspace(0, 3, 4, endpoint=False)
print(arr_no_end)

[  10.           46.41588834  215.443469   1000.        ]
[1. 2. 4. 8.]
[  1.           5.62341325  31.6227766  177.827941  ]


In [19]:
# Creating a 2x3 zero matrix, useful for initializing weights in ML or placeholders.
arr = np.zeros((2, 3), dtype=int)
print(arr)

# Variation: 3D array
arr_3d = np.zeros((2, 2, 2))
print(arr_3d)

# Edge case: Scalar shape (0D)
scalar_zero = np.zeros(())
print(scalar_zero)

[[0 0 0]
 [0 0 0]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
0.0


In [20]:
import numpy as np

# Creating a 3x2 ones array, useful for bias terms or masks.
arr = np.ones((3, 2), dtype=float)
print(arr)


[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# Variation: Integer dtype for counting
arr_int = np.ones((2,), dtype=int)
print(arr_int)