In [1]:
%pip install numpy

     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.8 kB ? eta -:--:--
     ------------------------- ------------ 41.0/60.8 kB 388.9 kB/s eta 0:00:01
     -------------------------------------- 60.8/60.8 kB 538.3 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
    --------------------------------------- 0.3/12.9 MB 8.3 MB/s eta 0:00:02
   -- ------------------------------------- 0.8/12.9 MB 10.0 MB/s eta 0:00:02
   ---- ----------------------------------- 1.3/12.9 MB 10.6 MB/s eta 0:00:02
   ----- ---------------------------------- 1.9/12.9 MB 10.9 MB/s eta 0:00:02
   ------- -------------------------------- 2.4/12.9 MB 11.1 MB/s eta 0:00:01
   --------- ------------------------------ 3.2/12.9 MB 11.3 MB/s eta 0:00:01
   ----------- ---------------------------- 3.7/12.9 MB 11.3 MB/s eta 0:00:01
   ------------- -------------------------- 4.3/12.9 MB 11.4 MB/s eta 0:00:01
  


[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: C:\Users\admin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
print(np.__version__)

2.2.1


In [5]:
# create a array 

data = np.array(23)
print(data)

# check type of array 

# type()
print(type(data))


23
<class 'numpy.ndarray'>


In [11]:
# 1 D array
data = np.array([21,22,23,24])
print(data)
print(data.ndim)

[21 22 23 24]
1


In [20]:
# 2d array
data = np.array([[11,22,33,44],[55,66,77,88],[99,32,34,35]])
print(data)
print(data.ndim)
print(data[1,2])

[[11 22 33 44]
 [55 66 77 88]
 [99 32 34 35]]
2
77


In [13]:
# 3d array 
data = np.array([[[1,2,3],[4,5,6],[7,8,10]],[[1,2,3],[4,5,6],[7,8,10]]])
print(data)
print(data.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8 10]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8 10]]]
3


In [16]:
arr_nd = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
print(arr_nd)

print(arr_nd.ndim)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
4


In [18]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])  # Access the first element (1)
print(arr[2])  # Access the third element (3)

1
3
