In [1]:
import numpy as np

In [3]:
# Checking NumPy Version 
print(np.__version__)

1.26.0


In [8]:
# Creating NumPy Arrays 
arr = np.array(42)
# check type
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
42


In [17]:
# 1-D Arrays:
arr = np.array([23,33,44,55])
print(arr)
# Check Number of Dimensions
print(arr.ndim)

[23 33 44 55]
1


In [16]:
# 2-D Arrays
arr = np.array([[3,4,5,6],[6,7,8,9]])
print(arr)
# Check Number of Dimensions
print(arr.ndim)

[[3 4 5 6]
 [6 7 8 9]]
2


In [21]:
# 3-D Arrays:
arr = np.array([[[3,4,5,6],[6,7,8,9]],[[5,6,7,8],[5,6,7,8]]])
print(arr)

[[[3 4 5 6]
  [6 7 8 9]]

 [[5 6 7 8]
  [5 6 7 8]]]


In [15]:
# Check Number of Dimensions
print(arr.ndim)

3


In [20]:
# Higher-Dimensional Arrays :
arr_nd = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
print(arr_nd)
# Check Number of Dimensions
print(arr_nd.ndim)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
4


In [24]:
# Basic Indexing
# index                    0  1  2  3  4
arr =            np.array([1, 2, 3, 4, 5])
# Negative Index          -5 -4 -3 -2 -1
print(arr[0])  # Access the first element (1)
print(arr[2])  # Access the third element (3)
# Negative Index 
print(arr[-1])  # Access the last element (5)
print(arr[-2])  # Access the second-to-last element (4)

1
3
5
4


In [28]:
# Multidimensional Array Indexing 
arr_2d = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])

print(arr_2d[0, 1]) # Access element at row 1, column 2 (6)

# Using a single tuple of indices
indices = (1, 2)
print(arr_2d[indices])  # Access the same element (6)

2
6
