In [9]:
import numpy as np
data = np.array([[34,45,56,78],[12,33,55,66]])
print(data)
print(data[1][2])
print(data.ndim)
print(data.shape)

[[34 45 56 78]
 [12 33 55 66]]
55
2
(2, 4)


In [29]:
from numpy import random
x = random.randint(100)
print(x)

1


In [51]:
data = random.rand()
print(data)

0.6271634338915667


In [72]:
x = random.randint(100,size=(5))
print(x)
print(type(x))

[77 73 77 69 94]
<class 'numpy.ndarray'>


In [75]:
x = random.randint(100,size=(3,3))
print(x)

[[46 28 92]
 [14 70 66]
 [26 20 38]]


In [76]:
x = random.rand(5)
print(x)

[0.34584727 0.549842   0.89454109 0.56937073 0.331538  ]


In [93]:
x = random.rand(5,3,5,4)
print(x)

print(x.ndim)

[[[[0.31180247 0.01065746 0.10336326 0.17459379]
   [0.20908351 0.97761816 0.92974484 0.92285996]
   [0.16639165 0.43598091 0.76947425 0.7925302 ]
   [0.11461689 0.71630218 0.7794276  0.9507517 ]
   [0.42589131 0.74003573 0.48490151 0.48665715]]

  [[0.7348397  0.28985807 0.97161177 0.23840245]
   [0.54231105 0.26466036 0.47155361 0.08217949]
   [0.26344055 0.96126956 0.49642069 0.20269164]
   [0.98978546 0.25208676 0.44122076 0.38232284]
   [0.15172397 0.91834892 0.55530397 0.29563416]]

  [[0.136319   0.30363038 0.48190775 0.63456864]
   [0.2817231  0.36468858 0.82539554 0.89108842]
   [0.64155674 0.31430119 0.46179566 0.29053227]
   [0.16411868 0.40300355 0.97715048 0.26382449]
   [0.11509616 0.06746309 0.99563981 0.77342293]]]


 [[[0.62475916 0.062351   0.86042129 0.30626489]
   [0.25646063 0.89573612 0.32134588 0.43179792]
   [0.93193498 0.81809775 0.2031923  0.58157341]
   [0.81760096 0.53396525 0.61343738 0.08764794]
   [0.84479076 0.67994683 0.62941519 0.81172452]]

  [[0.1324

In [115]:
x = random.choice([3,4,5,6,7])
print(x)

7


In [127]:
x = random.choice([3,4,5,6,7],size=(3,3))
print(x)

[[5 4 3]
 [3 7 5]
 [3 4 3]]
