In [3]:
# random 
from numpy import random


In [7]:
# int number
x = random.randint(100)
print(x)

60


In [9]:
# float number
x = random.rand()
print(x)

0.9444858455970198


In [12]:
# generate random array 
x = random.randint(100,size=(5))
print(x)

[76 81 98 65 74]


In [15]:
# generate 2d array 
x = random.randint(100,size=(3,3))
print(x)

[[50 45 22]
 [14 82 54]
 [73 88 83]]


In [17]:
# random Float Array
x = random.rand(5)
print(x)

[0.81173095 0.77182317 0.37743948 0.55023515 0.84265935]


In [18]:
# random float array 
x = random.rand(3,3)
print(x)

[[0.00466752 0.77687889 0.01852043]
 [0.3759398  0.45097632 0.84130423]
 [0.00457531 0.43558056 0.89860511]]


In [20]:
# single values
x = random.choice([2,3,4,15,16,17])
print(x)

15


In [23]:
# 2d array value 
x = random.choice([2,3,4,15,16,17] ,size=(2,3))
print(x)

[[15  4  2]
 [ 4  3  3]]


In [27]:
from numpy import random
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Shuffle the array in-place
random.shuffle(arr)

# Print the shuffled array
print(arr)

[2 4 5 1 3]


In [29]:
from numpy import random
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Generate a random permutation of the array
permuted_arr = random.permutation(arr)

# Print the random permutation
print(permuted_arr)

[2 3 4 5 1]
