In [ ]:
%pip install numpy

In [ ]:
import numpy as np

data = np.array([12,13,14,15,16,17])

print(data[3])
print(data[-2])


# Slicing
print(data[1:4])
print(data[:4])
print(data[2:])
print(data[:])


In [ ]:
data_2d = np.array([
    [21,22,23],
    [24,25,26],
    [27,28,29]
]) 
print(data_2d)
print(data_2d.ndim)
print(data_2d.shape)

print(data_2d[1,1])
print(data_2d[0,1])

# access 2nd col
print(data_2d[:,1])
print(data_2d[0,:])

In [33]:
arr_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr_3d)

# Ellipsis (...)
# print(arr_3d[...,0])
print(arr_3d[...,1])
print(arr_3d.ndim)

print(arr_3d[0][1][0:])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[2 4]
 [6 8]]
3
[3 4]


In [18]:
arr_4d = np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[1,2],[3,4]],[[5,6],[7,8]]]])
print(arr_4d)

# Ellipsis (...)
print(arr_4d[...,0])
# print(arr_4d[...,1])
print(arr_4d.ndim)

[[[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]


 [[[1 2]
   [3 4]]

  [[5 6]
   [7 8]]]]
[[[1 3]
  [5 7]]

 [[1 3]
  [5 7]]]
4


In [26]:
arr_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr_3d)
print(arr_3d.shape)
print(arr_3d[1][0,1])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
6


In [28]:
arr_4d = np.array([[[[1,2],[3,4]],[[5,6],[7,8]]],[[[10,12],[13,14]],[[15,16],[17,18]]]])
print(arr_4d)
print(arr_4d.shape)
print(arr_4d[1][0][0,1])

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[10 12]
   [13 14]]

  [[15 16]
   [17 18]]]]
(2, 2, 2, 2)
12


In [37]:
#reshape()

data = np.array([11,12,13,14,15,16,23,24,25,28])
new_r = data.reshape(5,2)
print(new_r)

[[11 12]
 [13 14]
 [15 16]
 [23 24]
 [25 28]]
