In [2]:
# install numpy

%pip install numpy
# !pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
# 1d Array

arr1 = np.array([21,22,23,24,25])
print(arr1)

[21 22 23 24 25]


In [5]:
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)
print(arr1.ndim)

(5,)
5
int32
1


In [6]:
# 2d Array

arr2 = np.array([[21,22,23],[24,25,26]])
print(arr2)

[[21 22 23]
 [24 25 26]]


In [7]:
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)
print(arr2.ndim)

(2, 3)
6
int32
2


In [8]:
# 3d Array

arr3 = np.array([[[21,22,23],[24,25,26]],[[21,22,23],[24,25,26]]])
print(arr3)

[[[21 22 23]
  [24 25 26]]

 [[21 22 23]
  [24 25 26]]]


In [9]:
print(arr3.shape)
print(arr3.size)
print(arr3.dtype)
print(arr3.ndim)

(2, 2, 3)
12
int32
3


In [10]:
# 4d Array
arr4 = np.array([[[[21,22,23],[24,25,26]],[[21,22,23],[24,25,26]]],[[[21,22,23],[24,25,26]],[[21,22,23],[24,25,26]]]])
print(arr4)

[[[[21 22 23]
   [24 25 26]]

  [[21 22 23]
   [24 25 26]]]


 [[[21 22 23]
   [24 25 26]]

  [[21 22 23]
   [24 25 26]]]]


In [11]:
print(arr4.shape)
print(arr4.size)
print(arr4.dtype)
print(arr4.ndim)

(2, 2, 2, 3)
24
int32
4


In [12]:
# zeros array 
zero = np.zeros((3,3))
print(zero)

one_arr = np.ones((2,4))
print(one_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
range_arr = np.arange(1,10)
print(range_arr)

[1 2 3 4 5 6 7 8 9]


In [14]:
range_arr = np.arange(1,10,2)
print(range_arr)

[1 3 5 7 9]


In [15]:
# randoms

randoms_arr =  np.random.rand(3,3)
print(randoms_arr)

[[0.49485756 0.27877231 0.03747132]
 [0.62381444 0.08718967 0.15684959]
 [0.14140763 0.89711299 0.16357791]]


In [16]:
data = np.array([[21,22,23],[25,45,67],[44,78,90]])
print(data)

print(data.ndim)

print(data[1,2])

[[21 22 23]
 [25 45 67]
 [44 78 90]]
2
67


In [17]:
data = np.array([21,22,23,24])
print(data+2)
print(data*3)
print(data**4)

[23 24 25 26]
[63 66 69 72]
[194481 234256 279841 331776]


In [18]:
# Mathematical functions
print(data.sum())
print(data.mean())
print(data.max())
print(data.min())

90
22.5
24
21


In [19]:
print(np.sin(data))
print(np.log(data))
print(np.exp(data))

[ 0.83665564 -0.00885131 -0.8462204  -0.90557836]
[3.04452244 3.09104245 3.13549422 3.17805383]
[1.31881573e+09 3.58491285e+09 9.74480345e+09 2.64891221e+10]


In [20]:
# Statistical functions
print(np.median(data))
print(np.std(data))
print(np.var(data))

22.5
1.118033988749895
1.25


In [38]:
# Slicing in Multidimensional Arrays
arr_2d = np.array([[1, 2, 3], [4, 5, 6],[21,22,23],[44,55,66]])
print(arr_2d[1, 2])  # Access element at row 1, column 2 (6)

6


In [47]:
print(arr_2d)
print("----------")
print(arr_2d[2:3])

[[ 1  2  3]
 [ 4  5  6]
 [21 22 23]
 [44 55 66]]
----------
[[21 22 23]]


In [67]:
print(arr_2d[1,:2])
print(arr_2d[2,1:])

[4 5]
[22 23]


In [48]:
print(arr_2d[1,2])

6


In [64]:
print(arr_2d[2,0:2])

[21 22]


In [71]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d)

print(arr_3d.ndim)
print(arr_3d[..., 1])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
[[2 4]
 [6 8]]


In [74]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

print(arr.size)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
6
(2, 3)


In [84]:
arr = np.array([1, 2, 3, 4, 5, 6,7,8,9,7,8,9])
reshaped = arr.reshape(4,3) 
print(reshaped)

reshaped = arr.reshape(2,6) 
print(reshaped)


reshaped = arr.reshape(2,2,3) 
print(reshaped)



[[1 2 3]
 [4 5 6]
 [7 8 9]
 [7 8 9]]
[[1 2 3 4 5 6]
 [7 8 9 7 8 9]]
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]]]


In [86]:
arr = np.array([1, 2, 3, 4, 5, 6])
sub_arrays = np.array_split(arr, 2) 
print(sub_arrays)

[array([1, 2, 3]), array([4, 5, 6])]


In [88]:
# NumPy Searching Arrays :

arr = np.array([1, 2, 3, 4, 5])
indexes = np.where(arr == 3)  # Find the index where value is 3
print(indexes)

(array([2], dtype=int64),)


In [91]:
data = np.array([[1, 2, 3], [4, 5, 6],[21,22,23],[44,55,66]])
print(np.where(data==55))

print(data[3,1])

(array([3], dtype=int64), array([1], dtype=int64))
55


In [97]:
arr = np.array([3, 1, 2, 4, 5])
arr.sort()
print(arr)

[1 2 3 4 5]


In [102]:
# NumPy Filtering Arrays 
arr = np.array([1, 2, 3, 4, 5,5,6,7,8,9,10])
condition = arr > 3
print(condition)

if True:
    print(arr**2)
 

[False False False  True  True  True  True  True  True  True  True]
[  1   4   9  16  25  25  36  49  64  81 100]


In [ ]:
data=list(np.arange(0.1,0.4,0.1).round(1))
print(data)


[0.1, 0.2, 0.3, 0.4]
