In [2]:
# install numpy in python

%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.1.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

print(np.__version__)

2.3.1


In [6]:
#  create a array
my_list = [12,13,14,15,16] 
data = np.array(my_list)
print(data)

# check type
print(type(data))

print(data.ndim)

[12 13 14 15 16]
<class 'numpy.ndarray'>
1


In [9]:
# 3x3 = 9
arr2 = np.array([[21,22,23],[24,25,26],[27,28,29]])
print(arr2)
print(arr2.ndim)

[[21 22 23]
 [24 25 26]
 [27 28 29]]
2


In [13]:
#3d array
arr2 = np.array(
    [
    [[21,22,23],[24,25,26],[27,28,29]],
    [[21,22,23],[24,25,26],[27,28,29]]
    ]
    )
print(arr2)
print(arr2.ndim)

[[[21 22 23]
  [24 25 26]
  [27 28 29]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
3


In [14]:
#4d array
arr2 = np.array(
    [
    [[[21,22,23],[24,25,26],[27,28,29]],
    [[21,22,23],[24,25,26],[27,28,29]]],
    [[[21,22,23],[24,25,26],[27,28,29]],
    [[21,22,23],[24,25,26],[27,28,29]]]
    ]
    )
print(arr2)
print(arr2.ndim)

[[[[21 22 23]
   [24 25 26]
   [27 28 29]]

  [[21 22 23]
   [24 25 26]
   [27 28 29]]]


 [[[21 22 23]
   [24 25 26]
   [27 28 29]]

  [[21 22 23]
   [24 25 26]
   [27 28 29]]]]
4


In [15]:
#  create a array
my_list = [12,13,14,15,16] 
data = np.array(my_list)
print(data)
# access data 
print(data[2])

[12 13 14 15 16]
14


In [ ]:
# 3x3 = 9
arr2 = np.array([[21,22,23],[24,25,26],[27,28,29]])
print(arr2)
print(arr2.ndim)
print(arr2[1,2])

[[21 22 23]
 [24 25 26]
 [27 28 29]]
2
26
