In [ ]:
%pip install numpy
# !pip install numpy

In [ ]:
# import numpy
import numpy as np
print(np.__version__)

# array 
data = np.array(23)
print(data)
print(type(data))

# 1d array 

my_list = [12,13,14,15,16,17,18,19]
data = np.array(my_list)
print(data)
print(data.ndim)

In [ ]:
# 2d
data_2d = np.array([
    [21,22,23],
    [24,25,26],
    [27,28,29]
]) 
print(data_2d)
print(data_2d.ndim)
print(data_2d.shape)

In [18]:
data_3d = np.array(
   [
    [
        [12,13,14],
        [15,16,17],
        [18,19,20]
    ],
    [
        [21,22,23],
        [24,25,26],
        [27,28,29]
    ]
   ]
)

print(data_3d)
print(data_3d.size)
print(data_3d.shape)

[[[12 13 14]
  [15 16 17]
  [18 19 20]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
18
(2, 3, 3)


In [22]:
data_4d = np.array(
    [
        [[
            [2,3],
            [2,3]
        ],
        [
            [2,3],
            [2,3]
        ]],
        [[
            [21,13],
            [24,25]
        ],
        [
            [34,45],
            [45,56]
        ]]
    ]
)

print(data_4d)
print(data_4d.ndim)
print(data_4d.shape)

[[[[ 2  3]
   [ 2  3]]

  [[ 2  3]
   [ 2  3]]]


 [[[21 13]
   [24 25]]

  [[34 45]
   [45 56]]]]
4
(2, 2, 2, 2)
